### ISSUE TITLE
Proposal: using svg as templates

### ISSUE THREAD

**Issue by rapzo** [carbon-design-system/carbon-icons-angular#10]
Since Angular CLI 7+ that svgs can be used as templates. Wouldn't it be a better option for this module?
Icons could be imported with little transformations from the original source and would have better props handling.
What do you think?

**Comment by cal-smith** [comment]
We still need to support icons as directives (`<svg iconName>`) so I'm not totally sure how that would work with the SVG directly in the template.

Icons as components work fine for simple usecases, but the host element causes issues with positioning and styling in most other situations.

**Comment by cal-smith** [comment]
I'm going to close this since we have icon directives that cover this usecase
