### ISSUE TITLE
Incorrect `bundles` and `main` paths in `package.json` since v11

### ISSUE THREAD

**Issue by gkalpak** [carbon-design-system/carbon-icons-angular#15]
The v11 releases of `@carbon/icons-angular` have incorrect paths for the `bundles` and `main` properties in `package.json`.
Instead of pointing to `bundles/carbon-icons-angular.umd.js` they point to `bundles/carbon-components-angular.js` (which does not exist).

This seems to have been broken in 0593da09bc6c5a5e3bf141d5a6c86e910111ff3b:

https://github.com/carbon-design-system/carbon-icons-angular/blob/6f0a8ba848ff28dc1d4b1fd83a7b22329293f4d3/src/generate.js#L280-L281

##
For reference, we ran into this while testing `@carbon/icons-angular` against the latest Angular compatibility compiler (ngcc): angular/ngcc-validation#1182

**Comment by cal-smith** [comment]
Thanks! I'll definitely be updating that next week ... We're having some issues with `ngcc` compilation size and multiple entry points when we apply a fix to enable the library to function with Angular 7 and 8 ... Any suggestions? Having `ngcc` recompile 1,000+ icons doesn't seem amazing, and we definitely need to support Angular <=9

**Comment by gkalpak** [comment]
Thx for taking a look. Can you be more specific on what issues you run into with `ngcc`? I am afraid `ngcc` is currently the only way in which libraries can be consumed by both ViewEngine and Ivy apps.

**Comment by cal-smith** [comment]
I'll see if I can make a PR into ngcc-validation with a `@next` version @gkalpak ... The main concern is that a single bundle is too large for `ngcc` to compile efficiently (1,000 icons in one bundle), but splitting up to one entry point per-icon _also_ results in a fairly lengthy `ngcc` process (1,000 individual compiles) ... I've seen times of ~3mins for `@next` to compile, and others have reported longer times (15min). 

The ideal I think, would be if `ngcc` or the `ngcc` webpack plugin would only compile the entry points that are used. Alternatively if there was some way for me to publish a pre-ngcc'd package, that would also solve our build-time issues.

**Comment by gkalpak** [comment]
I'm afraid there is currently no way to skip compiling the package when running ngcc over `node_modules/` but then compile the entry-points (i.e. icons) you need. We are investigating ways to improve that (for cases such as this where there are many entry-points but only few are used by the app). You can follow our progress in angular/angular#37075.

Shipping pre-ngcc's packages is also not an option, because the ngcc version has to match the Angular version used in the consuming app. So, if you shipped a pre-ngcc's package, it would only work reliably for consuming apps that use the same Angular version.

**Comment by cal-smith** [comment]
Aw, totally makes sense though ... I'll definitely follow #37075 👍 Thanks!

**Comment by cal-smith** [comment]
Fixed with 11.2.1
