### ISSUE TITLE
Unable to find BotModule for bot icon

### ISSUE THREAD

**Issue by DicksonTauro** [carbon-design-system/carbon-icons-angular#17]
![image](https://user-images.githubusercontent.com/20536239/83394611-81138f80-a416-11ea-865b-09cef57cbb53.png)

Tried to import module related to Bot icon, but unable find module named BotModule. If Module Not exists in library please add or if exists please provide alternative module name and path, which will be helpful for importing module.

Thanks

**Comment by cal-smith** [comment]
It's possible this is only available in a newer version of `@carbon/icons` than the one we're using! I'll have to publish an update to use `10.12.0` 👍

**Comment by cal-smith** [comment]
Try `v11.2.1`!
