### ISSUE TITLE
problem with style when icon is a div element

### ISSUE THREAD

**Issue by huineng** [carbon-design-system/carbon-icons-angular#26]
the svg looses it's fill when used as component

```
<!-- this displays well -->
<svg ibmIconAdd size="32"></svg>
<!-- this looses color -->
<ibm-icon-add size="32"></ibm-icon-add>
<!-- ... -->
```

reason ...

using the directives meets the class 

```
.bx--header__action > svg {
    fill: #ffffff;
}
```

but using the directive is adding an element that is not a div

```
div > p | Selects all <p> elements where the parent is a <div> element
```

so the directive is not styled via that class

![image](https://user-images.githubusercontent.com/3482445/87224133-b8982480-c350-11ea-9ec3-b7833c9d8623.png)

![image](https://user-images.githubusercontent.com/3482445/87224144-c483e680-c350-11ea-9004-d720b702ce3c.png)

![image](https://user-images.githubusercontent.com/3482445/87224150-cea5e500-c350-11ea-9aa3-7d593f357bef.png)

**Comment by cal-smith** [comment]
Yes, this is a known issue with using the icon component form. In most cases the directive form should be preferred.
