### ISSUE TITLE
Carbon Icons ng build --prod errors in v11

### ISSUE THREAD

**Issue by chaseoli** [carbon-design-system/carbon-icons-angular#33]
Using Angular 8 with '@carbon/icons-angular' v11 errors when running prod build `ng build --prod`

Example of when issue occurs - https://github.com/chaseoli/app-icon-issue/commit/d4fa723ece7be22c36ec58207eb5e5887a7207a2

Error Message using Wallet Icon (although it happens with all icons):
`ERROR in Unexpected value 'WalletModule in /home/chaseo/repos/carbon-icons-issue/app-icon-issue/node_modules/@carbon/icons-angular/wallet/index.d.ts' imported by the module 'AppModule in /home/chaseo/repos/carbon-icons-issue/app-icon-issue/src/app/app.module.ts'. Please add a @NgModule annotation.`

**Comment by cal-smith** [comment]
Angular 7 and 8 may have more success with v12 ... Angular 9 and 10 should work well with `v11`

**Comment by cal-smith** [comment]
I'm going to close this 👍

**Comment by pickle-weasle** [comment]
@cal-smith I can see on the releases page for v12 you mention 'Breaking Change'
Pardon my ignorance, but is this version still safe to use?

https://github.com/carbon-design-system/carbon-icons-angular/releases

**Comment by cal-smith** [comment]
Perfectly safe to use, the "breaking change" simply refers to the lower level packaging changes. As stated elsewhere v12 is best for Angular 7 and 8, while v11 is best for Angular 9 and 10 ... Somewhat confusing I know, but that's how the versions ended up ¯\_(ツ)_/¯
