### ISSUE TITLE
Ivy fails

### ISSUE THREAD

**Issue by huineng** [carbon-design-system/carbon-icons-angular#34]
angular 10 
carbon angular icons 11

i get the following error when using ngcc

is this something that can be solved ?

``
Compiling @carbon/icons-angular : esm5 as esm5
Error: Error on worker #1: Error: Invariant violated: No format-path or format for /home/travis/build/myproject/node_modules/@carbon/icons-angular : main (formatPath: ./bundles/carbon-components-angular.js | format: undefined)
    at /home/travis/build/myproject/node_modules/@angular/compiler-cli/ngcc/src/execution/create_compile_function.js:44:27
    at /home/travis/build/myproject/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:85:54
    at step (/home/travis/build/myproject/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:140:27)
    at Object.next (/home/travis/build/myproject/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:121:57)
    at /home/travis/build/myproject/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/travis/build/myproject/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:110:16)
    at Worker.<anonymous> (/home/travis/build/myproject/node_modules/@angular/compiler-
``

**Comment by huineng** [comment]
for some reason version 11.1.4 didn't show in my npm , but that fixed it

**Comment by huineng** [comment]
too soon the issue is still there 

```
Compiling @carbon/icons-angular/Q/H : fesm5 as esm5
Compiling @carbon/icons-angular/Q/H : esm2015 as esm2015
Compiling @carbon/icons-angular/Q/H : esm5 as esm5
Error: Error on worker #5: Error: Invariant violated: No format-path or format for /Users/Documents/workspace/lab/carbon-etl/applications/etl-mgr/node_modules/@carbon/icons-angular/Q/H : main (formatPath: ../../bundles/Q/H.umd.js | format: undefined)
```

**Comment by cal-smith** [comment]
`v11.2.0` was just released ... definitely give that a try 👍

**Comment by cal-smith** [comment]
`v11.2.1` should be the one that works!

**Comment by cal-smith** [comment]
Just checked, this should be resolved 👍
