### ISSUE TITLE
Please upgrade to Angular 10

### ISSUE THREAD

**Issue by Me262a** [carbon-design-system/carbon-icons-angular#41]
warning " > @carbon/icons-angular@11.0.1" has incorrect peer dependency "@angular/compiler@^7.0.0 || ^8.0.0 || ^9.0.0".
warning " > @carbon/icons-angular@11.0.1" has incorrect peer dependency "@angular/core@^7.0.0 || ^8.0.0 || ^9.0.0".

**Comment by stanislavgeorgiev** [comment]
+1

**Comment by cal-smith** [comment]
Fixed with `v11.2.0`
