### ISSUE TITLE
Build Error: Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by pesiqueira** [carbon-design-system/carbon-icons-angular#42]
I'm getting this error when run the build 
ERROR in : Unexpected value 'DownloadModule in /Users/plino/Documents/Projects/ecfgcloud-app-frontend/node_modules/@carbon/icons-angular/download/index.d.ts' imported by the module 'ManageRepositoryModule in /Users/plino/Documents/Projects/ecfgcloud-app-frontend/src/app/manage-repository/manage-repository.module.ts'. Please add a @NgModule annotation.

But when I run the serve its ok

I'm importing just like this:
@NgModule({
/*******/
 imports: [
        .....
        DownloadModule,
        UploadModule
    ],
/******/
})

I'm using this versions
"@angular/cli": "7.3.8"
"@angular/compiler": "7.2.12"
"@angular/core": "7.2.12"
"@carbon/icons-angular": "^11.2.0"

**Comment by cal-smith** [comment]
Does `@carbon/icons-angular@12` fix things for you? Angular 7 and 8 likely work best with v12, while Angular 9 and 10 work best with v11

**Comment by pesiqueira** [comment]
Perfect! I change the version and it work well!! Thank you !

**Comment by alexisibm** [comment]
I have the dependencies as follow:

  "dependencies": {
    "@angular/animations": "~10.1.2",
    "@angular/common": "~10.1.2",
    "@angular/compiler": "~10.1.2",
    "@angular/core": "~10.1.2",
    "@angular/forms": "~10.1.2",
    "@angular/platform-browser": "~10.1.2",
    "@angular/platform-browser-dynamic": "~10.1.2",
    "@angular/router": "~10.1.2",
    "@apollo/client": "^3.0.0",
    "@carbon/icons-angular": "^11.2.1",
    "apollo-angular": "^2.1.0",
    "carbon-components": "^10.24.0",
    "carbon-components-angular": "^4.27.6",
    "graphql": "^15.0.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },

I'm still getting the "Please add a @NgModule annotation." error

**Comment by cal-smith** [comment]
Can you share the error you're getting @alexisibm?

**Comment by sanjitbauli** [comment]
@cal-smith - i strongly believe it should be mentioned in the readme file.
