### ISSUE TITLE
Could you please suggest the best way to have icons bigger than 32 pixel?

### ISSUE THREAD

**Issue by bitforcesrl** [carbon-design-system/carbon-icons-angular#6]
I've seen the template generated and there is no icons in the array greater than 32 so it's impossible to use a bigger icons. How can i do that?

many thanks

![Screenshot 2020-02-10 at 11 17 12](https://user-images.githubusercontent.com/46250701/74142508-5e583380-4bf9-11ea-8b1d-301856923ca2.png)

**Comment by cal-smith** [comment]
You should be able to apply a class with a `width`/`height` to override the size ... that said the icons are designed to preform best at specific sizes, so if you can stay within the given sizes that would be ideal.

**Comment by bitforcesrl** [comment]
In our design we've welcome pages when you have empty lists (eg: projects) and we've bigger icons, there. I've tried with classes but there are some problems with the viewbox and the border of the icons become too thick

**Comment by cal-smith** [comment]
You may want to look into manually including pictograms in that case :+1: The icons _are_ designed with the specified sizes in mind
