### ISSUE TITLE
Not all carbon design pictograms are available

### ISSUE THREAD

**Issue by bitforcesrl** [carbon-design-system/carbon-icons-angular#7]
Hi, looking at the available icons exported as module there aren't all pictograms listed here
https://www.carbondesignsystem.com/guidelines/pictograms/library/

could you please give us infos about how to have all carbon icons ? thanks

**Comment by cal-smith** [comment]
Pictograms are different to Icons ... at the moment this library only supports Icons. In the future the goal is to have a `@carbon/pictograms-angular` package that exposes the pictograms from `@carbon/pictograms` ... https://www.carbondesignsystem.com/guidelines/icons/library is the link to reference for _icons_

**Comment by bitforcesrl** [comment]
So the only solution available now is download the svgs and use them straight in the code right?

**Comment by cal-smith** [comment]
Correct, we should have a `pictograms-angular` in the next couple months
